[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Sepolia testnet configuration
[rpc_endpoints]
sepolia = "https://ethereum-sepolia.publicnode.com"

# Etherscan configuration for contract verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }

# General settings
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200
via_ir = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
