[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version   = "0.8.30"

# General settings
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200
via_ir = false

# 0x9dA94A5e96D876Cf80BFc7C68a898c97d576aFC8
# forge script script/DeployMarkets.s.sol \
#   --rpc-url https://eth-sepolia.g.alchemy.com/v2/euJp53PODQmQLSIuUpjlcMeQNtUBEtvT \
#   --private-key 0x4f8e6104a0fffe3687d6a88ede5905a3a384a1e1f36986ca4f7f6db529b982c5 \
#   --broadcast \
#   --use 0.8.30+commit.73712a01
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# forge script script/DeployMarkets.s.sol --rpc-url sepolia --private-key private_key --broadcast